import type { Metadata } from 'next'
import GlobalStyle from './globalStyle'
import Header from './components/Header'

import { Inter } from 'next/font/google'
 
const inter = Inter({
  subsets: ['latin'],
  display: 'swap',
})
 

export const metadata: Metadata = {
  title: 'Programação RPC',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <GlobalStyle/>
        <Header/>
        {children}
      </body>
    </html>
  )
}
